apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat-admin-ui
  namespace: librechat
  labels:
    app: librechat-admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librechat-admin-ui
  template:
    metadata:
      labels:
        app: librechat-admin-ui
    spec:
      containers:
        - name: admin-ui
          image: ghcr.io/sidekickmachines/librechat-admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
