apiVersion: v1
kind: Service
metadata:
  name: librechat-admin-ui
  namespace: librechat
  labels:
    app: librechat-admin-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: librechat-admin-ui
