apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-admin
  namespace: librechat
  labels:
    app: oauth2-proxy-admin
spec:
  type: ClusterIP
  ports:
    - port: 4180
      targetPort: 4180
      protocol: TCP
      name: http
  selector:
    app: oauth2-proxy-admin
